name = 'MFunkyB'
license = 'MIT'
licenselink = 'https://github.com/simi/mfunkyb/LICENSE'
description = 'mysterious green theme'

# The home page of the theme, where the source can be found
homepage = 'https://github.com/simi/mfunkyb'

# If you have a running demo of the theme
demosite = 'https://owner.github.io/repo'

# Taxonomy terms
tags = ['blog']
features = ['anims']

# If the theme has a single author
[author]
  name = 'retro'
  homepage = 'https://github.com/simi'
